//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Suat Karakusoglu
//

import Foundation

enum ___VARIABLE_productName:identifier___ViewEvent: ViewEvent {

}

enum ___VARIABLE_productName:identifier___PresenterCommand: PresenterCommand {

}

enum ___VARIABLE_productName:identifier___InteractorRequest: InteractorRequest {

}

enum ___VARIABLE_productName:identifier___InteractorResponse: InteractorResponse {

}

