//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Suat Karakusoglu
//

import UIKit

final class ___VARIABLE_productName:identifier___Interactor: Interactor {

    typealias Response = ___VARIABLE_productName:identifier___InteractorResponse
    typealias Request = ___VARIABLE_productName:identifier___InteractorRequest

    var responseListener: AnyResponseListener<___VARIABLE_productName:identifier___InteractorResponse>?

    init() {
        // Inject api services here from arguments
    }

    func handle(request: ___VARIABLE_productName:identifier___InteractorRequest) {
        switch request {

        }
    }
}
