//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Suat Karakusoglu
//

import UIKit.UIViewController
import UIKit.UINavigationController

extension ArenaType
{
    func build___VARIABLE_productName:identifier___() -> UIViewController {
        let viewController = ___VARIABLE_productName:identifier___ViewController()
        let presenter = ___VARIABLE_productName:identifier___Presenter()
        let interactor = ___VARIABLE_productName:identifier___Interactor()

        self.build(
          view: viewController,
          presenter: presenter,
          interactor: interactor)

        presenter.router = ___VARIABLE_productName:identifier___Router(arenaPresenter: viewController)

        return viewController
    }
}
